# Makefile for echo client and server

CXX=			g++ $(CCFLAGS)

THREADING=		threading.o
OBJS =			$(THREADING)

LIBS= -pthread

CCFLAGS= -g -std=c++11 

all:	threading

threading:$(THREADING)
	$(CXX) -o threading $(THREADING) $(LIBS)

clean:
	rm -f $(OBJS) $(OBJS:.o=.d)

realclean:
	rm -f $(OBJS) $(OBJS:.o=.d) threading


# These lines ensure that dependencies are handled automatically.
%.d:	%.cc
	$(SHELL) -ec '$(CC) -M $(CPPFLAGS) $< \
		| sed '\''s/\($*\)\.o[ :]*/\1.o $@ : /g'\'' > $@; \
		[ -s $@ ] || rm -f $@'

include	$(OBJS:.o=.d)
